# Step 1. Rebuild the source code only when needed
# FROM oven/bun:1 AS builder
FROM node:20-slim AS builder
# Set NODE_OPTIONS to increase memory limit
ENV NODE_OPTIONS="--max-old-space-size=8192"
ENV VITE_SCALAR_REST_URL=https://testnet.nodeapi.scalar.org
ENV VITE_REOWN_CLOUD_PROJECT_ID=
ENV VITE_MEMPOOL_API=https://mempool.space
# install required packages for slim image
RUN apt-get update && apt-get install -y g++ gcc make python3 && rm -rf /var/lib/apt/lists/*
RUN npm install -g bun 

WORKDIR /app
COPY package.json ./
# Install dependencies with bun
# RUN bun install --no-optional || bun add -d node-gyp && bun install --no-optional
RUN bun add -d node-gyp && bun install --no-optional
# Fix bug Could not resolve require("./src/build/**/*/DTraceProviderBindings")
RUN cp -r /app/node_modules/dtrace-provider/build /app/node_modules/dtrace-provider/src

COPY src ./src
COPY public ./public
COPY index.html ./
COPY components.json ./
COPY tsconfig.app.json ./
COPY tsconfig.json ./
COPY tsconfig.node.json ./
COPY vite.config.ts ./
COPY .env ./
EXPOSE 5173

ENTRYPOINT [ "bun", "run", "dev" ]

