export enum ELiquidityModel {
  UNSPECIFIED = "LIQUIDITY_MODEL_UNSPECIFIED",
  POOL = "LIQUIDITY_MODEL_POOL",
  UPC = "LIQUIDITY_MODEL_UPC",
}

export enum EProtocolStatus {
  UNSPECIFIED = "STATUS_UNSPECIFIED",
  ACTIVATED = "STATUS_ACTIVATED",
  DEACTIVATED = "STATUS_DEACTIVATED",
  PENDING = "STATUS_PENDING",
}
