/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtocolsIndexRouteImport } from './routes/protocols/index'
import { Route as FaucetIndexRouteImport } from './routes/faucet/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as ProtocolsMeRouteImport } from './routes/protocols/me'
import { Route as ProtocolsSlugRouteImport } from './routes/protocols/$slug'
import { Route as ExploreTransferIndexRouteImport } from './routes/explore/transfer/index'
import { Route as ExploreStatisticIndexRouteImport } from './routes/explore/statistic/index'
import { Route as ExploreRedeemIndexRouteImport } from './routes/explore/redeem/index'
import { Route as ExploreBridgeIndexRouteImport } from './routes/explore/bridge/index'
import { Route as ExploreTransferSlugIndexRouteImport } from './routes/explore/transfer/$slug/index'
import { Route as ExploreRedeemSlugIndexRouteImport } from './routes/explore/redeem/$slug/index'
import { Route as ExploreBridgeSlugIndexRouteImport } from './routes/explore/bridge/$slug/index'
import { Route as ExploreTransferSlugStatusRouteImport } from './routes/explore/transfer/$slug/$status'
import { Route as ExploreRedeemSlugStatusRouteImport } from './routes/explore/redeem/$slug/$status'
import { Route as ExploreBridgeSlugStatusRouteImport } from './routes/explore/bridge/$slug/$status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsIndexRoute = ProtocolsIndexRouteImport.update({
  id: '/protocols/',
  path: '/protocols/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaucetIndexRoute = FaucetIndexRouteImport.update({
  id: '/faucet/',
  path: '/faucet/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsMeRoute = ProtocolsMeRouteImport.update({
  id: '/protocols/me',
  path: '/protocols/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsSlugRoute = ProtocolsSlugRouteImport.update({
  id: '/protocols/$slug',
  path: '/protocols/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreTransferIndexRoute = ExploreTransferIndexRouteImport.update({
  id: '/explore/transfer/',
  path: '/explore/transfer/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreStatisticIndexRoute = ExploreStatisticIndexRouteImport.update({
  id: '/explore/statistic/',
  path: '/explore/statistic/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRedeemIndexRoute = ExploreRedeemIndexRouteImport.update({
  id: '/explore/redeem/',
  path: '/explore/redeem/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreBridgeIndexRoute = ExploreBridgeIndexRouteImport.update({
  id: '/explore/bridge/',
  path: '/explore/bridge/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreTransferSlugIndexRoute =
  ExploreTransferSlugIndexRouteImport.update({
    id: '/explore/transfer/$slug/',
    path: '/explore/transfer/$slug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExploreRedeemSlugIndexRoute = ExploreRedeemSlugIndexRouteImport.update({
  id: '/explore/redeem/$slug/',
  path: '/explore/redeem/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreBridgeSlugIndexRoute = ExploreBridgeSlugIndexRouteImport.update({
  id: '/explore/bridge/$slug/',
  path: '/explore/bridge/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreTransferSlugStatusRoute =
  ExploreTransferSlugStatusRouteImport.update({
    id: '/explore/transfer/$slug/$status',
    path: '/explore/transfer/$slug/$status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExploreRedeemSlugStatusRoute = ExploreRedeemSlugStatusRouteImport.update({
  id: '/explore/redeem/$slug/$status',
  path: '/explore/redeem/$slug/$status',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreBridgeSlugStatusRoute = ExploreBridgeSlugStatusRouteImport.update({
  id: '/explore/bridge/$slug/$status',
  path: '/explore/bridge/$slug/$status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/protocols/$slug': typeof ProtocolsSlugRoute
  '/protocols/me': typeof ProtocolsMeRoute
  '/explore': typeof ExploreIndexRoute
  '/faucet': typeof FaucetIndexRoute
  '/protocols': typeof ProtocolsIndexRoute
  '/explore/bridge': typeof ExploreBridgeIndexRoute
  '/explore/redeem': typeof ExploreRedeemIndexRoute
  '/explore/statistic': typeof ExploreStatisticIndexRoute
  '/explore/transfer': typeof ExploreTransferIndexRoute
  '/explore/bridge/$slug/$status': typeof ExploreBridgeSlugStatusRoute
  '/explore/redeem/$slug/$status': typeof ExploreRedeemSlugStatusRoute
  '/explore/transfer/$slug/$status': typeof ExploreTransferSlugStatusRoute
  '/explore/bridge/$slug': typeof ExploreBridgeSlugIndexRoute
  '/explore/redeem/$slug': typeof ExploreRedeemSlugIndexRoute
  '/explore/transfer/$slug': typeof ExploreTransferSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/protocols/$slug': typeof ProtocolsSlugRoute
  '/protocols/me': typeof ProtocolsMeRoute
  '/explore': typeof ExploreIndexRoute
  '/faucet': typeof FaucetIndexRoute
  '/protocols': typeof ProtocolsIndexRoute
  '/explore/bridge': typeof ExploreBridgeIndexRoute
  '/explore/redeem': typeof ExploreRedeemIndexRoute
  '/explore/statistic': typeof ExploreStatisticIndexRoute
  '/explore/transfer': typeof ExploreTransferIndexRoute
  '/explore/bridge/$slug/$status': typeof ExploreBridgeSlugStatusRoute
  '/explore/redeem/$slug/$status': typeof ExploreRedeemSlugStatusRoute
  '/explore/transfer/$slug/$status': typeof ExploreTransferSlugStatusRoute
  '/explore/bridge/$slug': typeof ExploreBridgeSlugIndexRoute
  '/explore/redeem/$slug': typeof ExploreRedeemSlugIndexRoute
  '/explore/transfer/$slug': typeof ExploreTransferSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/protocols/$slug': typeof ProtocolsSlugRoute
  '/protocols/me': typeof ProtocolsMeRoute
  '/explore/': typeof ExploreIndexRoute
  '/faucet/': typeof FaucetIndexRoute
  '/protocols/': typeof ProtocolsIndexRoute
  '/explore/bridge/': typeof ExploreBridgeIndexRoute
  '/explore/redeem/': typeof ExploreRedeemIndexRoute
  '/explore/statistic/': typeof ExploreStatisticIndexRoute
  '/explore/transfer/': typeof ExploreTransferIndexRoute
  '/explore/bridge/$slug/$status': typeof ExploreBridgeSlugStatusRoute
  '/explore/redeem/$slug/$status': typeof ExploreRedeemSlugStatusRoute
  '/explore/transfer/$slug/$status': typeof ExploreTransferSlugStatusRoute
  '/explore/bridge/$slug/': typeof ExploreBridgeSlugIndexRoute
  '/explore/redeem/$slug/': typeof ExploreRedeemSlugIndexRoute
  '/explore/transfer/$slug/': typeof ExploreTransferSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/protocols/$slug'
    | '/protocols/me'
    | '/explore'
    | '/faucet'
    | '/protocols'
    | '/explore/bridge'
    | '/explore/redeem'
    | '/explore/statistic'
    | '/explore/transfer'
    | '/explore/bridge/$slug/$status'
    | '/explore/redeem/$slug/$status'
    | '/explore/transfer/$slug/$status'
    | '/explore/bridge/$slug'
    | '/explore/redeem/$slug'
    | '/explore/transfer/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/protocols/$slug'
    | '/protocols/me'
    | '/explore'
    | '/faucet'
    | '/protocols'
    | '/explore/bridge'
    | '/explore/redeem'
    | '/explore/statistic'
    | '/explore/transfer'
    | '/explore/bridge/$slug/$status'
    | '/explore/redeem/$slug/$status'
    | '/explore/transfer/$slug/$status'
    | '/explore/bridge/$slug'
    | '/explore/redeem/$slug'
    | '/explore/transfer/$slug'
  id:
    | '__root__'
    | '/'
    | '/protocols/$slug'
    | '/protocols/me'
    | '/explore/'
    | '/faucet/'
    | '/protocols/'
    | '/explore/bridge/'
    | '/explore/redeem/'
    | '/explore/statistic/'
    | '/explore/transfer/'
    | '/explore/bridge/$slug/$status'
    | '/explore/redeem/$slug/$status'
    | '/explore/transfer/$slug/$status'
    | '/explore/bridge/$slug/'
    | '/explore/redeem/$slug/'
    | '/explore/transfer/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtocolsSlugRoute: typeof ProtocolsSlugRoute
  ProtocolsMeRoute: typeof ProtocolsMeRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  FaucetIndexRoute: typeof FaucetIndexRoute
  ProtocolsIndexRoute: typeof ProtocolsIndexRoute
  ExploreBridgeIndexRoute: typeof ExploreBridgeIndexRoute
  ExploreRedeemIndexRoute: typeof ExploreRedeemIndexRoute
  ExploreStatisticIndexRoute: typeof ExploreStatisticIndexRoute
  ExploreTransferIndexRoute: typeof ExploreTransferIndexRoute
  ExploreBridgeSlugStatusRoute: typeof ExploreBridgeSlugStatusRoute
  ExploreRedeemSlugStatusRoute: typeof ExploreRedeemSlugStatusRoute
  ExploreTransferSlugStatusRoute: typeof ExploreTransferSlugStatusRoute
  ExploreBridgeSlugIndexRoute: typeof ExploreBridgeSlugIndexRoute
  ExploreRedeemSlugIndexRoute: typeof ExploreRedeemSlugIndexRoute
  ExploreTransferSlugIndexRoute: typeof ExploreTransferSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols/': {
      id: '/protocols/'
      path: '/protocols'
      fullPath: '/protocols'
      preLoaderRoute: typeof ProtocolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faucet/': {
      id: '/faucet/'
      path: '/faucet'
      fullPath: '/faucet'
      preLoaderRoute: typeof FaucetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols/me': {
      id: '/protocols/me'
      path: '/protocols/me'
      fullPath: '/protocols/me'
      preLoaderRoute: typeof ProtocolsMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols/$slug': {
      id: '/protocols/$slug'
      path: '/protocols/$slug'
      fullPath: '/protocols/$slug'
      preLoaderRoute: typeof ProtocolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/transfer/': {
      id: '/explore/transfer/'
      path: '/explore/transfer'
      fullPath: '/explore/transfer'
      preLoaderRoute: typeof ExploreTransferIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/statistic/': {
      id: '/explore/statistic/'
      path: '/explore/statistic'
      fullPath: '/explore/statistic'
      preLoaderRoute: typeof ExploreStatisticIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/redeem/': {
      id: '/explore/redeem/'
      path: '/explore/redeem'
      fullPath: '/explore/redeem'
      preLoaderRoute: typeof ExploreRedeemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/bridge/': {
      id: '/explore/bridge/'
      path: '/explore/bridge'
      fullPath: '/explore/bridge'
      preLoaderRoute: typeof ExploreBridgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/transfer/$slug/': {
      id: '/explore/transfer/$slug/'
      path: '/explore/transfer/$slug'
      fullPath: '/explore/transfer/$slug'
      preLoaderRoute: typeof ExploreTransferSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/redeem/$slug/': {
      id: '/explore/redeem/$slug/'
      path: '/explore/redeem/$slug'
      fullPath: '/explore/redeem/$slug'
      preLoaderRoute: typeof ExploreRedeemSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/bridge/$slug/': {
      id: '/explore/bridge/$slug/'
      path: '/explore/bridge/$slug'
      fullPath: '/explore/bridge/$slug'
      preLoaderRoute: typeof ExploreBridgeSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/transfer/$slug/$status': {
      id: '/explore/transfer/$slug/$status'
      path: '/explore/transfer/$slug/$status'
      fullPath: '/explore/transfer/$slug/$status'
      preLoaderRoute: typeof ExploreTransferSlugStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/redeem/$slug/$status': {
      id: '/explore/redeem/$slug/$status'
      path: '/explore/redeem/$slug/$status'
      fullPath: '/explore/redeem/$slug/$status'
      preLoaderRoute: typeof ExploreRedeemSlugStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/bridge/$slug/$status': {
      id: '/explore/bridge/$slug/$status'
      path: '/explore/bridge/$slug/$status'
      fullPath: '/explore/bridge/$slug/$status'
      preLoaderRoute: typeof ExploreBridgeSlugStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtocolsSlugRoute: ProtocolsSlugRoute,
  ProtocolsMeRoute: ProtocolsMeRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  FaucetIndexRoute: FaucetIndexRoute,
  ProtocolsIndexRoute: ProtocolsIndexRoute,
  ExploreBridgeIndexRoute: ExploreBridgeIndexRoute,
  ExploreRedeemIndexRoute: ExploreRedeemIndexRoute,
  ExploreStatisticIndexRoute: ExploreStatisticIndexRoute,
  ExploreTransferIndexRoute: ExploreTransferIndexRoute,
  ExploreBridgeSlugStatusRoute: ExploreBridgeSlugStatusRoute,
  ExploreRedeemSlugStatusRoute: ExploreRedeemSlugStatusRoute,
  ExploreTransferSlugStatusRoute: ExploreTransferSlugStatusRoute,
  ExploreBridgeSlugIndexRoute: ExploreBridgeSlugIndexRoute,
  ExploreRedeemSlugIndexRoute: ExploreRedeemSlugIndexRoute,
  ExploreTransferSlugIndexRoute: ExploreTransferSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
